Standardize default energy offset in optics module
lnls-fac/pyaccel pull request #152
Opened 2024-09-10 13:30 UTC by vellosok75

When trying to calculate optics with `calc_edwards_teng`, I was getting bugs related to the default `None`-type energy-deviation. As in #149, I standardized `energy-offset` to `0.0`. I also did it for `calc_twiss`, despite the `None`-type not being a problem there.

2024-09-10 15:01 UTC, fernandohds564 requested changes

2024-09-12 17:04 UTC, vellosok75 commented on pyaccel/optics/twiss.py
> +        indices='open', energy_offset=0.0):
Done. Thanks!

2024-09-13 13:08 UTC, murilobalves approved these changes

2024-09-13 18:08 UTC, xresende approved these changes

2024-09-20 11:27 UTC, Gabrielrezende-asc approved these changes

2024-10-01 18:01 UTC, fernandohds564 approved these changes

2024-10-03 11:23 UTC, merged