Permits that generate_bunch accepts optical parameters from calc_edwards_teng
lnls-fac/pyaccel pull request #95
Opened 2021-11-05 19:09 UTC by jquentino

With this PR, generation_bunch accepts both Twiss and EdwardsTeng optical functions to generate a bunch.
I also change the function parameters names to agree with our recent paradigm in representing emittances at normal modes, that is:
```
emitx -> emit1 
emity -> emit2
twi -> optics
```

2021-11-05 19:13 UTC, anacso17 approved these changes

2021-11-05 19:23 UTC, fernandohds564 requested changes
Very nice @jquentino ! I have one comment in the code.
Have you tested this method in a machine with small coupling?

2021-11-05 19:23 UTC, fernandohds564 commented on pyaccel/tracking.py
> +    return _np.array((p_1, p_1p, p_2, p_2p, p_en, p_s))
The bunch should be returned in the laboratory frame of reference (x, x', y, y', de, dl) and not on the normal modes frame. I think you have to rotate back using the R matrix from Edwards&Teng decomposition.

2021-11-08 12:51 UTC, xresende approved these changes

2021-11-09 19:56 UTC, fernandohds564 approved these changes

2021-11-09 20:35 UTC, murilobalves approved these changes

2021-11-09 21:05 UTC, merged