Make naff accepts signal of any size, doc string update and 'is_real' bug
lnls-fac/pyaccel pull request #99
Opened 2021-11-30 21:21 UTC by jquentino

With this PR `pyaccel.naff.general_naff` doesn't more require an input signal with the size of the form `6*L-1`, where `L` is an integer.
Now the code automatically discards a minimum quantity of data to satisfy this condition.

I also would like to talk about a bug where the option `is real` of this same function is not working. An example:
```python
T = 10*np.pi # Space length
N = 100 # Number of points
t = np.linspace(0,T,num=N)
f = 0.4 # frequency
y = np.sin(2*np.pi*f*t) # Signal
s_r = N/T # Sample rate

freqs, fourier = pa.naff.naff_general(y, nr_ff=1, is_real=True, window=1)

print(s_r*freqs)
```
output: `-0.4040392872313213`

We get negative frequencies despite `is_real=True`.

I tried to search the reason for this, but the naff calculation is performed by `trackcpp` and I didn't know yet how to lead with this package and his connections with `pyaccel.tracking`.

So, as a probably not general solution, I add the following lines to `general_naff`:
```python
if is_real:
        freqs = _np.abs(freqs)
```
If someone has a better idea, feel free to commit this PR.

2021-12-03 20:25 UTC, xresende commented on pyaccel/naff.py
> +method, developed by J. Naskar in:
typo: Naskar -> Laskar

2021-12-10 16:58 UTC, fernandohds564 requested changes

2021-12-10 16:58 UTC, fernandohds564 commented on pyaccel/naff.py
> +        freqs[mask] = _np.abs(1-freqs[mask])
as we talked in Teams, I think it is better to remove this `if` statement and change documentation.

2021-12-10 23:33 UTC, anacso17 approved these changes

2021-12-13 13:35 UTC, fernandohds564 approved these changes
@jquentino, please remember to update the description so it serves as reference for future queries.

2021-12-13 18:35 UTC, merged